name: Docker Build and Deploy (Self-Hosted)

on:
  push:
    branches:
      - devops-branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t ecommerce-app .

    - name: Run Docker Compose
      run: |
        docker-compose down || true
        docker-compose up -d
